### ISSUE TITLE
Cache enable with a ttl value always returns cached data

### ISSUE THREAD

**Issue by n3cr0cr0w** [kevinoo/panorama-whois#4]
The TTL value is never checked to expire the cached results.

**Comment by kevinoo** [comment]
Hi @n3cr0cr0w 
I'm publishing the new version of the library, adding some new features:
- Cached whois responses
- OCR parser (images with email)
- Custom providers

**Comment by kevinoo** [comment]
**v0.5.0** released! :muscle: 

https://packagist.org/packages/kevinoo/panorama-whois#0.5.0
